import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layouts/Header";
import HeaderBanner from "@/components/layouts/HeaderBanner";
import ThemeToggle from "@/components/modules/common/ThemeToggle";
import Footer from "@/components/layouts/Footer";
import TermsAndCondition from "@/components/modules/home-page/TermsAndCondition";
import ExploreProperty from "@/components/modules/home-page/ExploreProperty";
import FooterMobile from "@/components/layouts/FooterMobile";

const urbanist = localFont({
  src: "../../public/fonts/Urbanist-VariableFont_wght.ttf",
  variable: "--font-urbanist",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Estatein",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className}`}>
        <ThemeToggle />
        <HeaderBanner />
        <Header />
        {children}
        <div className="dark:bg-grey-shade-8">
          <ExploreProperty />
          <Footer />
          <FooterMobile />
        </div>
        <div className="dark:bg-grey-shade-10 py-5">
          <TermsAndCondition />
        </div>
      </body>
    </html>
  );
}
